apiVersion: v1
kind: Service
metadata:
  name: apache-service
  labels:
    app: apacheserver
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30006
    protocol: TCP
  selector:
    app: apacheserver

